spring:
  application:
    name: profiles
  liquibase:
    parameters:
      textColumnType: VARCHAR(250)
  datasource:
    type: org.springframework.jdbc.datasource.SimpleDriverDataSource
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: secret

application:
  base-path: /api/v1

server:
  port: 8080
